# Locate LASTools.
# This module defines
# LASLIB_LIBRARY
# LASLIB_LIBRARY_DEBUG
# LASLIB_FOUND, if false, do not try to link to laslib
# LASLIB_INCLUDE_DIR, where to find the headers

FIND_PATH(LASLIB_INCLUDE_DIR lasreader.hpp
  $ENV{LASTOOLS_DIR}
  NO_DEFAULT_PATH
    PATH_SUFFIXES include
)

FIND_PATH(LASZIP_INCLUDE_DIR mydefs.hpp
  $ENV{LASTOOLS_DIR}
  NO_DEFAULT_PATH
    PATH_SUFFIXES include
)

FIND_LIBRARY(LASLIB_LIBRARY
  NAMES LASlib
  PATHS
    $ENV{LASTOOLS_DIR}
    NO_DEFAULT_PATH
    PATH_SUFFIXES lib64 lib
)

FIND_LIBRARY(LASLIB_LIBRARY_DEBUG
  NAMES LASlib_d LASlibd
  PATHS
    $ENV{LASTOOLS_DIR}
    NO_DEFAULT_PATH
    PATH_SUFFIXES lib64 lib
)

SET(LASTOOLS_FOUND "NO")
IF(LASLIB_INCLUDE_DIR AND LASLIB_LIBRARY AND LASZIP_INCLUDE_DIR)
  SET(LASTOOLS_FOUND "YES")
ENDIF(LASLIB_INCLUDE_DIR AND LASLIB_LIBRARY AND LASZIP_INCLUDE_DIR)

